.TH TOOMANYFILES 1 2018\-07\-24
.SH NAME

.B toomanyfiles:
Recover normal files and delete files from a partition.
.SH SYNOPSIS

toomanyfiles [\-\-help] [\-\-version] [\-\-nofiles] [ \-\-nodeleted| \-\-partition| \-\-output ]
.SH DESCRIPCI\('ON

.PP
This app has the following parameters.
.PP
.RS
.B \-\-nofiles
.RE
.PP
.RS
.RS
Scans the net of the interface parameter and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.RS
If a device is not known, it will be showed in red. Devices in green are trusted devices.
.RE
.RE
.PP
.RS
.B \-\-nodeleted
.RE
.PP
.RS
.RS
Allows to add a known device from console.
.RE
.RE
.PP
.RS
.B \-\-partition
.RE
.PP
.RS
.RS
Allows to remove a known device from console.
.RE
.RE
.PP
.RS
.B \-\-output
.RE
.PP
.RS
.RS
Shows all known devices in database from console.
.RE
.RE
