.TH TOOMANYFILES 1 2018\-07\-25
.SH NAME

.B toomanyfiles:
Recover normal files and delete files from a partition.
.SH SYNOPSIS

toomanyfiles [\-\-help] [\-\-version] [\-\-nofiles] [ \-\-nodeleted| \-\-partition| \-\-output ]
.SH DESCRIPTION

.PP
This app has the following parameters.
.PP
.RS
.B \-\-output
.RE
.PP
.RS
.RS
Shows all known devices in database from console.
.RE
.RE
